---
deployment:
  tasks:
    - source /home1/redisdi1/nodevenv/mediceen.app/22/bin/activate
    - cd /home1/redisdi1/mediceen.app/repos
    - npm install
    - npm run build
    - mkdir -p .output/tmp
    - touch .output/tmp/restart.txt
    - deactivate